Add a GH action that verifies deployment
vaadin/base-starter-flow-karaf pull request #74
Opened 2021-12-09 14:54 UTC by mstahv

Also removed travis conf as that is not needed (because we have GH actions and the configuration is not even functional)

2021-12-09 14:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/vaadin-flow-karaf-example?pullRequest=74) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/vaadin-flow-karaf-example?pullRequest=74) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/vaadin-flow-karaf-example?pullRequest=74) it.</sub>

2022-11-21 15:39 UTC, mcollovati requested changes

2022-11-21 15:39 UTC, mcollovati commented on .github/workflows/maven.yml
> +      run: mvn -B install --file pom.xml
Is `--file pom.xml` really needed? Shouldn't it be the default?

2022-11-21 15:39 UTC, mcollovati commented on .github/workflows/maven.yml
> +      run: mvn -B install --file pom.xml
```suggestion
      run: mvn -B install
```

2022-11-21 15:39 UTC, mcollovati commented on .github/workflows/maven.yml
> +      run: mvn -B -pl main-ui -am install -Ptest-deployment --file pom.xml
Is `--file pom.xml` really needed? Shouldn't it be the default?
Also `-am` should not be needed since we installed all modules in the previous step
```suggestion
      run: mvn -B -pl main-ui install -Ptest-deployment
```

2022-11-22 09:34 UTC, mstahv commented
I wonder why this hasn't been handled before? Don't expect me to work on this in near future, don't remember anything about this,  just take over the changes if this is now active.

2022-11-22 12:35 UTC, mcollovati approved these changes

2022-11-22 12:36 UTC, merged